repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--select, I, --fix]
        name: ruff-check-imports
      # Run the formatter.
      - id: ruff-format
        name: ruff-format 